WaiterShop/api/urls.py
from rest_framework import routers
from django.urls import path, include
from .views import ItemViewSet, CompanyList, ContactMessageCreate, add_to_cart, OrderSummary, remove_from_cart, remove_single_item_from_cart, CheckoutAPIView


app_name = "api"

router = routers.SimpleRouter()

router.register('products', ItemViewSet, basename='product')


urlpatterns = [
    path('',include(router.urls)),
    path('about-us/', CompanyList.as_view(), name = 'about_us'),
    path('contact-us/', ContactMessageCreate.as_view(), name = 'contact_us'),
    path('add-to-card/<slug:slug>', add_to_cart, name= 'add_to_card'),
    path('order-summary/', OrderSummary.as_view(), name = 'order-summary'),
    path('remove-from-cart/<slug:slug>', remove_from_cart, name = 'remove-from-cart'),
    path('remove-single-item/<slug:slug>', remove_single_item_from_cart, name = 'remove-single-item'),
    path('checkout/', CheckoutAPIView.as_view(), name = 'checkout'),


]

WaiterShop/company/urls.py
from django.urls import path
from .views import ContactUsView, AboutUsView


app_name = 'company'
urlpatterns = [
    path('contact-us', ContactUsView.as_view(),name = 'contact-us'),
    path('about-us', AboutUsView.as_view(),name = 'about-us'),

]

WaiterShop/config/urls.py
import debug_toolbar
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, re_path
from django.conf.urls import include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('company/', include('company.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include('api.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WaiterShop/core/urls.py
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import (HomeView, ItemDetailView, OrderSummaryView, 
                    add_to_cart, remove_from_cart, remove_single_item_from_cart,
                     CheckoutView, AddCouponView, PaymentView, RequestRefundView, ProductListView,
                      CategoryList, SearchList)

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/detail/<slug:slug>', ItemDetailView.as_view(), name='item_detail'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/page/<int:page>', ProductListView.as_view(), name='product-list'),
    path('products/<slug:slug>', CategoryList.as_view(), name='product-category'),
    path('products/<slug:slug>/page/<int:page>', CategoryList.as_view(), name='product-category'),
    path('search/', SearchList.as_view(), name="search"),
    path('search/page/<int:page>', SearchList.as_view(), name="search"),


]

WaiterShop/core/models.py
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.core.cache import cache
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating
from django.utils import timezone
from django.db.models import QuerySet, Manager




LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

TAG_CHOICES = (
    ('BO','BEST OFFER'),
    ('FD','FLASH DEALS'),
    ('LM','LAST MINUTE'),

)

class CustomQuerySet(QuerySet):
    def update(self, **kwargs):
        cache.delete('product_objects')
        super(CustomQuerySet, self).update(updated=timezone.now(), **kwargs)



class CategoryManager(models.Manager):
    
    def filter_active_category(self):
        active = self.filter(status=True)
        return active

class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیر دسته')
    title = models.CharField(max_length=150, verbose_name='عنوان دسته بندی')
    slug = models.SlugField(max_length=150, unique=True, verbose_name='ادرس دسته بندی')
    status = models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')
    position = models.IntegerField(default=0, verbose_name='پوزیشن')
    objects = CategoryManager()
    class Meta:
        verbose_name='دسته بندی'
        verbose_name_plural='دسته بندی ها'
        ordering=[ 'parent__id','position']

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class ItemManager(models.Manager):
    def filter_true_status(self):
        return self.filter(status=True)

    def get_queryset(self):
        return CustomQuerySet(self.model, using=self._db)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ManyToManyField(Category,max_length=100,related_name='items')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to='items_image')
    ratings = GenericRelation(Rating, related_name='item')
    publish = models.DateTimeField(default = timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)
    objects = ItemManager()

    def __str__(self):
        return self.title


    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def order_item_name(self):
        return f"{self.quantity} of {self.item.title}"
    order_item_name.short_description = 'name'

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class OrderManager(models.Manager):
    def get_false_ordered(self):
        return self.get(user=self.request.user, ordered=False)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    objects = OrderManager()

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return f"{self.pk}-{self.user.username}"

    def order_name(self):
        return f"{self.pk}-{self.user.username}"
    order_name.short_description = 'name'
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.IntegerField()
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.order}"


class LandingPageManager(models.Manager):
    def active_landing_page(self):
        return self.filter(status = True)


class LandingPageBanner(models.Model):
    tag = models.CharField(choices = TAG_CHOICES, max_length = 200)
    title = models.CharField(max_length = 200)
    status = models.BooleanField(default=False)
    objects = LandingPageManager()

    def __str__(self):
        return self.title

def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

WaiterShop/templates/shop/about-us.html
{% extends 'shared/base.html' %}
{% block content %}
<div class="page-heading about-heading header-text">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="text-content">
            <h4>about us</h4>
            <h2>our company</h2>
          </div>
        </div>
      </div>
    </div>
</div>


<div class="best-features about-features">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section-heading">
            <h2>Our Background</h2>
          </div>
        </div>
        <div class="col-md-6">
          <div class="right-image">
            <img src="{{ company.image.url }}" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="left-content">
            <h4>{{ company.title }}</h4>
            <p>{{ company.description }}</p>
            <ul class="social-icons">
              <li><a href="{{ company.social_media.facebook }}"><i class="fa fa-facebook"></i></a></li>
              <li><a href="{{ company.social_media.tweeter }}"><i class="fa fa-twitter"></i></a></li>
              <li><a href="{{ company.social_media.linkedin }}"><i class="fa fa-linkedin"></i></a></li>

            </ul>
          </div>
        </div>
      </div>
    </div>
</div>
  

<div class="team-members">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section-heading">
            <h2>Our Team Members</h2>
          </div>
        </div>

          {% for member in team_member %}

          <div class="col-md-4">
            <div class="team-member">
              <div class="thumb-container">
                <img src="{{ member.user.image.url }}" alt="">
                <div class="hover-effect">
                  <div class="hover-content">
                    <ul class="social-icons">
                      <li><a href="{{ member.user.social_media.facebook }}"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="{{ member.user.social_media.tweeter }}"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="{{ member.user.social_media.linkedin }}"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="down-content">
                <h4>{{ member.user.get_full_name }}</h4>
                <span>{{ member.get_position_display }}</span>
                <p>{{ member.user.bio }}</p>
              </div>
            </div>
          </div>

          {% endfor %}

      </div>
    </div>
</div>
{% endblock content %}

WaiterShop/templates/shop/category_list.html
{% extends 'shared/list.html' %}

{% block category %}
    {{ category.title }}
{% endblock category %}

{% block previous_page_url %}
    {% url 'core:product-category' category.slug page_obj.previous_page_number %}
{% endblock previous_page_url %}

{% block active_page %}
    {% url 'core:product-category' category.slug page %}
{% endblock active_page %}

{% block unactive_page %}
    {% url 'core:product-category' category.slug page %}
{% endblock unactive_page %}

{% block next_page_url %}
   {% url 'core:product-category' category.slug page_obj.next_page_number %} 
{% endblock next_page_url %}

WaiterShop/templates/shop/checkout.html
{% extends 'shared/base.html' %}
{% block content %}
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>
              <hr>
              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <label for="shipping_address" class="">Address</label>
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                </div>

                <div class="md-form mb-5">
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>


          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">
            {% include 'shared/order_snippet.html' %}
        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
{% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");


use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

</script>
{% endblock extra_scripts %}

WaiterShop/templates/shop/home.html
{% extends 'shared/base.html' %}
{% load ratings %}
{% load static %}
{% block HeadTitle %} WaiterShop | Home {% endblock HeadTitle %} 
{% block content %}
    <!-- Banner Starts Here -->
    <div class="banner header-text">
      <div class="owl-banner owl-carousel">
        {% for slide in landing_page %}
        <div class="banner-item-0{{ forloop.counter }}">
          <div class="text-content">
            <h4>{{ slide.get_tag_display }}</h4>
            <h2>{{ slide.title }}</h2>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <!-- Banner Ends Here -->

    <div class="latest-products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Latest Products</h2>
              <a href="{% url 'core:product-list' %}">view all products <i class="fa fa-angle-right"></i></a>
            </div>
          </div>
          {% for item in object_list %}
          <div class="col-md-4">
            <div class="product-item">
              <a href="{% url 'core:item_detail' item.slug %}"><img src="{{ item.image.url }}" class="" alt=""></a>
              <div class="down-content">
                <a href="{% url 'core:item_detail' item.slug %}"><h4>{{ item.title }}</h4></a>
                <h6>${{ item.price }}</h6>
                <p>{{ item.description }}</p>
                {% ratings item %}
                <span>Reviews (24)</span>
              </div>
            </div>
          </div>
          {% endfor %}

          </div>
        </div>
      </div>
    </div>

    <div class="best-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>About Waiter Shop</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <h4>Looking for the best products?</h4>
              <p><a rel="nofollow" href="https://templatemo.com/tm-546-sixteen-clothing" target="_parent">This template</a> is free to use for your business websites. However, you have no permission to redistribute the downloadable ZIP file on any template collection website. <a rel="nofollow" href="https://templatemo.com/contact">Contact us</a> for more info.</p>
              <ul class="featured-list">
                <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                <li><a href="#">Consectetur an adipisicing elit</a></li>
                <li><a href="#">It aquecorporis nulla aspernatur</a></li>
                <li><a href="#">Corporis, omnis doloremque</a></li>
                <li><a href="#">Non cum id reprehenderit</a></li>
              </ul>
              <a href="{% url 'company:about-us' %}" class="filled-button">Read More</a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
              {% for item in company %}
              <img src="media/{{ item.image }}" alt="">
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <div class="row">
                <div class="col-md-8">
                  <h4>Creative &amp; Unique <em>Sixteen</em> Products</h4>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque corporis amet elite author nulla.</p>
                </div>
                <div class="col-md-4">
                  <a href="{% url 'core:product-list' %}" class="filled-button">Purchase Now</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

WaiterShop/templates/shop/item_detail.html
{% extends 'shared/base.html' %}
{% load ratings %}
{% block content %}
<div class="single-product">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h1>Detail Of Product</h1>
          </div>
        </div>
        <div class="col-md-6">
          <div class="product-slider">
            <div id="slider" class="flexslider">
              
            <div class="flex-viewporttwo" style="overflow: hidden; position: relative;"><ul class="slides" style="width: 800%; transition-duration: 0s; transform: translate3d(0px, 0px, 0px);">
                <li class="flex-active-slide" style="width: 498px; height:500px; margin-right: 0px; float: left; display: block;">
                  <img src="{{ object.image.url }}" class="picsize"  draggable="false">
                </li>
                <!-- items mirrored twice, total of 12 -->
              </ul></div></div>
            <div id="carousel" class="flexslider">
              
            <div class="flex-viewporttwo" style="overflow: hidden; position: relative;"><ul class="slides" style="width: 800%; transition-duration: 0s; transform: translate3d(0px, 0px, 0px);"></ul>

            </div></div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="right-content">
            <h4>{{ object.title }}</h4>
            <h6>${{ object.price }}</h6>
            <p>{{ object.description }}</p>
            <span>7 left on stock</span>
            <form action="" method="get">
              <label for="quantity">Quantity:</label>
              <input name="quantity" type="quantity" class="quantity-text" id="quantity" onfocus="if(this.value == '1') { this.value = ''; }" onblur="if(this.value == '') { this.value = '1';}" value="1">
              <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                Add to cart
                <i class="fa fa-shopping-cart ml-1"></i>
              </a>
            </form>
            <div class="down-content">
              <div class="categories">
                
                <h6>Category:{% for category in object.category.get_active_category %} <span><a href="{% url 'core:product-category' category.slug %}">{{ category.title }} ,</a></span>{% endfor %}</h6>
                
              </div>
              <hr>
              {% ratings object %}
              <div class="share">
                <h6>Share: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 
{% endblock content %}

WaiterShop/templates/shop/order_summary.html
{% extends 'shared/base.html' %}
{% block content %}
<main class="mt-5 pt-5">
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Item title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total Item Price</th>
            </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fa fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fa fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fa fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
</main>
{% endblock content %}

WaiterShop/templates/shop/product_list.html
{% extends 'shared/list.html' %}

{% block previous_page_url %}
    {% url 'core:product-list' page_obj.previous_page_number %}
{% endblock previous_page_url %}

{% block active_page %}
    {% url 'core:product-list' page %}
{% endblock active_page %}

{% block unactive_page %}
    {% url 'core:product-list' page %}
{% endblock unactive_page %}

{% block next_page_url %}
   {% url 'core:product-list' page_obj.next_page_number %} 
{% endblock next_page_url %}

WaiterShop/templates/shop/request_refund.html
{% extends 'shared/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<main class="mt-5 pt-5">
    <div class="container">

    <h2 class="mb-3">Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
</main>

{% endblock content %}

WaiterShop/templates/shop/search_list.html
{% extends 'shared/list_without_banner.html' %}

{% block search %}
    {{ search }}
{% endblock search %}

{% block previous_page_url %}
    {% url 'core:search' page_obj.previous_page_number %}?q={{search}}
{% endblock previous_page_url %}

{% block active_page %}
    {% url 'core:search' page %}?q={{search}}
{% endblock active_page %}

{% block unactive_page %}
    {% url 'core:search' page %}?q={{search}}
{% endblock unactive_page %}

{% block next_page_url %}
   {% url 'core:search' page_obj.next_page_number %} ?q={{search}}
{% endblock next_page_url %}