WaiterShop/api/urls.py
from rest_framework import routers
from django.urls import path, include
from .views import ItemViewSet, CompanyList, ContactMessageCreate, add_to_cart, OrderSummary, remove_from_cart, remove_single_item_from_cart, CheckoutAPIView


app_name = "api"

router = routers.SimpleRouter()

router.register('products', ItemViewSet, basename='product')


urlpatterns = [
    path('',include(router.urls)),
    path('about-us/', CompanyList.as_view(), name = 'about_us'),
    path('contact-us/', ContactMessageCreate.as_view(), name = 'contact_us'),
    path('add-to-card/<slug:slug>', add_to_cart, name= 'add_to_card'),
    path('order-summary/', OrderSummary.as_view(), name = 'order-summary'),
    path('remove-from-cart/<slug:slug>', remove_from_cart, name = 'remove-from-cart'),
    path('remove-single-item/<slug:slug>', remove_single_item_from_cart, name = 'remove-single-item'),
    path('checkout/', CheckoutAPIView.as_view(), name = 'checkout'),


]

WaiterShop/company/urls.py
from django.urls import path
from .views import ContactUsView, AboutUsView


app_name = 'company'
urlpatterns = [
    path('contact-us', ContactUsView.as_view(),name = 'contact-us'),
    path('about-us', AboutUsView.as_view(),name = 'about-us'),

]

WaiterShop/config/urls.py
import debug_toolbar
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, re_path
from django.conf.urls import include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('company/', include('company.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include('api.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WaiterShop/core/urls.py
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import (HomeView, ItemDetailView, OrderSummaryView, 
                    add_to_cart, remove_from_cart, remove_single_item_from_cart,
                     CheckoutView, AddCouponView, PaymentView, RequestRefundView, ProductListView,
                      CategoryList, SearchList)

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/detail/<slug:slug>', ItemDetailView.as_view(), name='item_detail'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/page/<int:page>', ProductListView.as_view(), name='product-list'),
    path('products/<slug:slug>', CategoryList.as_view(), name='product-category'),
    path('products/<slug:slug>/page/<int:page>', CategoryList.as_view(), name='product-category'),
    path('search/', SearchList.as_view(), name="search"),
    path('search/page/<int:page>', SearchList.as_view(), name="search"),


]

WaiterShop/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

    <title>{% block HeadTitle %} WaiterShop {% endblock HeadTitle %}</title>
    {% block extra_head %}
    {% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="{% static "shop/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
<!--

TemplateMo 546 Sixteen Clothing

https://templatemo.com/tm-546-sixteen-clothing

-->

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static "shop/assets/css/fontawesome.css" %}">
    <link rel="stylesheet" href="{% static "shop/assets/css/templatemo-sixteen.css" %}">
    <link rel="stylesheet" href="{% static "shop/assets/css/owl.css" %}">
    <link rel="stylesheet" href="{% static "shop/assets/css/rtl.css" %}">


  </head>

  <body>
    
    
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
      <div class="jumper">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>  
    <!-- ***** Preloader End ***** -->
    
    {% if messages %}
    <div class="mt-5 pt-5">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
        </div>
    {% endif %}

    <!-- Header -->
    <header class="fixed-top">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'core:home' %}"><h2>Waiter <em>Shop</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item{% if request.path == '/' %} active{% endif %}">
                <a class="nav-link" href="{% url 'core:home' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item{% if request.path == '/products/' %} active{% endif %}">
                <a class="nav-link" href="{% url 'core:product-list' %}">Our Products</a>
              </li>
              <li class="nav-item{% if request.path == '/company/about-us' %} active{% endif %}">
                <a class="nav-link" href="{% url 'company:about-us' %}">About Us</a>
              </li>
              <li class="nav-item{% if request.path == '/company/contact-us' %} active{% endif %}">
                <a class="nav-link" href="{% url 'company:contact-us' %}">Contact Us</a>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="/admin/logout/"> Log out </a>
              </li>  
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="/accounts/login/"> Log in </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/accounts/signup/"> Sign up</a>
              </li>            
              {% endif %}

              <li>
                <form class="searchform" action="{% url 'core:search' %}">
                  <input class="searchinput" name="q" type="search" placeholder="Search">
                  <i class="searchfa fa fa-search"></i>
                </form>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    {% block content %}{% endblock content %}
    <!-- End Page Content -->
    
    {% include 'shared/footer.html' %}

    {% include 'shared/scripts.html' %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  </body>

</html>

WaiterShop/templates/shared/base_account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block head_title %}{% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    {% block extra_head %} {% endblock %}
    <!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static "account/images/icons/favicon.ico" %}" />
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "account/vendor/bootstrap/css/bootstrap.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "account/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "account/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "account/vendor/animate/animate.css" %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static "account/vendor/css-hamburgers/hamburgers.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "account/vendor/animsition/css/animsition.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "account/vendor/select2/select2.min.css" %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static "account/vendor/daterangepicker/daterangepicker.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "account/css/util.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "account/css/main.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "account/css/rtl.css" %}">

<!--===============================================================================================-->
</head>
<body>
    
    {% if messages %}
    <div class="mt-5 pt-5">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
        </div>
    {% endif %}


    {% block content %}{% endblock content %}


    {% block extra_body %} {% endblock %}
	
<!--===============================================================================================-->
	<script src="{% static "account/vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "account/vendor/animsition/js/animsition.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "account/vendor/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "account/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "account/vendor/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "account/vendor/daterangepicker/moment.min.js" %}"></script>
	<script src="{% static "account/vendor/daterangepicker/daterangepicker.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "account/vendor/countdowntime/countdowntime.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "account/js/main.js" %}"></script>
    {% block extra_scripts %} {% endblock extra_scripts %}
</body>
</html>

WaiterShop/templates/shared/footer.html
<footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="inner-content">
            <p>Copyright &copy; 2020 Sixteen Clothing Co., Ltd.
          
          - Design: <a rel="nofollow noopener" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
          </div>
        </div>
      </div>
    </div>
</footer>

WaiterShop/templates/shared/list.html
{% extends 'shared/base.html' %}
{% load ratings %}
{% block content %}
<div class="page-heading products-heading header-text">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="text-content">
            <h4>{% block category %}All Products{% endblock category %}</h4>
            <h2>WaiterShop Products</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="products">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="filters">
            <ul>
              {% for category in categories %}
                <li class="active" data-filter="*"><a href="{% url 'core:product-category' category.slug %}">{{ category.title }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-md-12">
          <div class="filters-content">
              <div class="row grid" style="position: relative; height: 767.782px;">
                  {% for item in object_list %}
                    <div class="col-lg-4 col-md-4 all des" style="position: absolute; left: 0%; top: 0px;">
                    <div class="product-item">
                      <a href="{% url 'core:item_detail' item.slug %}"><img src="{{ item.image.url }}" alt=""></a>
                      <div class="down-content">
                        <a href="#"><h4>{{ item.title }}</h4></a>
                        <h6>${{ item.price }}</h6>
                        <p>{{ item.description }}</p>
                        <ul class="stars">
                          {% ratings item %}
                        </ul>
                        <span>Reviews (12)</span>
                      </div>
                    </div>
                    </div>
                  {% endfor %}
              </div>
          </div>
        </div>
        <div class="col-md-12">
          <ul class="pages">
            {% if page_obj.has_previous %}
            <li><a href="{% block previous_page_url %}{% endblock %}"><i class="fa fa-angle-double-left"></i></a></li>
            {% endif %}
            {% for page in paginator.page_range %}
              {% if page == page_obj.number %}
              <li class="active"><a href="{% block active_page %}{% endblock %}">{{ page }}</a></li>
              {% else %}
              <li><a href="{% block unactive_page %}{% endblock %}">{{ page }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li><a href="{% block next_page_url %}{% endblock %}"><i class="fa fa-angle-double-right"></i></a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

WaiterShop/templates/shared/list_without_banner.html
{% extends 'shared/base.html' %}
{% load ratings %}
{% block content %}
  <div class="products">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="filters">
            <ul>
              {% for category in categories %}
                <li class="active" data-filter="*"><a href="{% url 'core:product-category' category.slug %}">{{ category.title }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-md-12">
          <div class="section-heading">
            <h2>Search for :{% block search %}{% endblock search %}</h2>
          </div>
        </div>
        <div class="col-md-12">
          <div class="filters-content">
              <div class="row grid" style="position: relative; height: 767.782px;">
                  {% for item in object_list %}
                    <div class="col-lg-4 col-md-4 all des" style="position: absolute; left: 0%; top: 0px;">
                    <div class="product-item">
                      <a href="{% url 'core:item_detail' item.slug %}"><img src="{{ item.image.url }}" alt=""></a>
                      <div class="down-content">
                        <a href="#"><h4>{{ item.title }}</h4></a>
                        <h6>${{ item.price }}</h6>
                        <p>{{ item.description }}</p>
                        <ul class="stars">
                          {% ratings item %}
                        </ul>
                        <span>Reviews (12)</span>
                      </div>
                    </div>
                    </div>
                  {% endfor %}
              </div>
          </div>
        </div>
        <div class="col-md-12">
          <ul class="pages">
            {% if page_obj.has_previous %}
            <li><a href="{% block previous_page_url %}{% endblock %}"><i class="fa fa-angle-double-left"></i></a></li>
            {% endif %}
            {% for page in paginator.page_range %}
              {% if page == page_obj.number %}
              <li class="active"><a href="{% block active_page %}{% endblock %}">{{ page }}</a></li>
              {% else %}
              <li><a href="{% block unactive_page %}{% endblock %}">{{ page }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li><a href="{% block next_page_url %}{% endblock %}"><i class="fa fa-angle-double-right"></i></a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

WaiterShop/templates/shared/order_snippet.html
<div class="col-md-12 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description|truncatewords:20}}</small>
              </div>
              <span class="text-muted">${{ order_item.get_final_price }}</span>
            </li>
            {% endfor %}
            {% if order.coupon %}
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
              </div>
              <span class="text-success">-${{ order.coupon.amount }}</span>
            </li>
            {% endif %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${{ order.get_total }}</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          {% if DISPLAY_COUPON_FORM %}
          <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
            {% csrf_token %}
            <div class="input-group">
              {{ couponform.code }}
              <div class="input-group-append">
                <button class="btn btn-success btn-md waves-effect m-0" type="submit">Redeem</button>
              </div>
            </div>
          </form>
          {% endif %}
          
</div>

WaiterShop/templates/shared/scripts.html
{% load static %}
<!-- Bootstrap core JavaScript -->
<script src="{% static "shop/vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "shop/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>


<!-- Additional Scripts -->
<script src="{% static "shop/assets/js/custom.js" %}"></script>
<script src="{% static "shop/assets/js/owl.js" %}"></script>
<script src="{% static "shop/assets/js/slick.js" %}"></script>
<script src="{% static "shop/assets/js/isotope.js" %}"></script>
<script src="{% static "shop/assets/js/accordions.js" %}"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>


<script language = "text/Javascript"> 
  cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
  function clearField(t){                   //declaring the array outside of the
  if(! cleared[t.id]){                      // function makes it static and global
      cleared[t.id] = 1;  // you could use true and false, but that's more typing
      t.value='';         // with more chance of typos
      t.style.color='#fff';
      }
  }
</script>